WTH??? Y u no work?
Makes no sense.
Copy pasted and still does not work.

java.lang.IllegalArgumentException: Cannot set property
PropertyEnum{name=variant, clazz=class
appeng.core.skyfall.block.CertusInfusedBlock$CertusInfusedPropertyEnum,
values=[STONE]} as it does not exist in
BlockStateContainer{block=appliedenergistics3:certus_infused,
properties=[variant]}